# Site settings
title: Semantic Pingback
email: 
description: "Adding a social dimension to the Linked Data Web."
baseurl: "/SemanticPingback/"
url: "https://aksw.github.io/SemanticPingback/"
twitter_username: akswgroup
github_username:  aksw

# Build settings
markdown: kramdown
permalink: pretty
